import Head from "next/head";
import { ethers, Contract } from "ethers";
import abi from "../constants/abi.json";
import contractAddresses from "../constants/contractAddresses.json";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";
import { Form, useNotification } from "@web3uikit/core";

export default function Sell() {
  const { chainId: chainIdInHex } = useMoralis();

  const chainId = "31337" || parseInt(chainIdInHex).toString();
  const marketPlaceAddress = contractAddresses[chainId]["NFTMarketPlace"][0];

  const approveAndList = async (data) => {
    console.log("Approving...");
    console.log(data);
    const nftAddress = data.data[0].inputResult;
    const tokenId = data.data[1].inputResult;
    const price = data.data[2].inputResult;
    try {
      console.log(nftAddress, tokenId, price);
      const provider = new ethers.providers.Web3Provider(web3.currentProvider);
      const signer = provider.getSigner();

      const nftContract = new Contract(nftAddress, abi.BasicNFT, signer);

      const approveTx = await nftContract.approve(marketPlaceAddress, tokenId);
      await approveTx.wait();
      console.log("Approved to move NFTs");
      const marketPlace = new Contract(
        marketPlaceAddress,
        abi.NFTMarketPlace,
        signer
      );

      const listingTx = await marketPlace.listItem(
        nftAddress,
        tokenId,
        ethers.utils.parseEther(price)
      );
      await listingTx.wait();
    } catch (e) {
      console.log(e);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Market Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        onSubmit={approveAndList}
        data={[
          {
            inputWidth: "50%",
            name: "NFT Address",
            type: "text",
            value: "",
          },
          {
            inputWidth: "50%",
            name: "Token ID",
            type: "number",
            value: "",
          },
          {
            inputWidth: "50%",
            name: "Price (ETH)",
            type: "number",
            value: "",
          },
        ]}
        title="Sell Your NFT!"
      ></Form>
    </div>
  );
}
